import Login from '../login/page'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const dynamic = "force-dynamic"

export default async function RootLayout({ children }: {
  children: React.ReactNode
}) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { user }
  } = await supabase.auth.getUser()

  if (!user) {
    return <Login />
  }

  return (children)
}
