import Navbar from '@/components/Navbar'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const dynamic = "force-dynamic"

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <section className='bg-black'>
          <Navbar />
        </section>
        <main className="min-h-screen flex flex-col items-center bg-slate-800">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  )
}
